;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        end-of-buffer
        hungry-delete-forward
        my/hydra-switch-mode/body
        my/smarter-move-beginning-of-line
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        hungry-delete-backward
        org-kill-line
        org-refile
        ))
