;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-slash
        c-fill-paragraph
        c-indent-line-or-region
        cn/backward-whitespace
        cn/upcase-initials-word
        comment-dwim
        counsel-M-x
        decrement-number-at-point
        electric-newline-and-maybe-indent
        end-of-buffer
        forward-whitespace
        hungry-delete-forward
        increment-number-at-point
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        kill-region-or-backward-word
        my/hydra-switch-mode/body
        my/smarter-move-beginning-of-line
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        org-yank
        repeat
        sp-splice-sexp
        xah-toggle-letter-case
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        hungry-delete-backward
        kmacro-end-or-call-macro
        org-export-dispatch
        org-kill-line
        org-refile
        ))
